; ── Default connection (used by all client PCs) ──────────────────────
[Default]
Server=IT-PC\SQLITDEV
Database=SnapSearchDb
User=AES:nEWjSCtbnMeRmOOC8ZbTBY9QPfF9nzs3cskIj4h/jFo=
Password=AES:fiDBekL1Z1lGIMbned2o8timbFf9e2CBXxTSqKr4f/4=
Encrypt=true
TrustServerCertificate=true

; ── Per-machine overrides (only needed for devs with local SQL) ───────
[Machine_LAPTOP131-D]
Server=LAPTOP131-D\MSSQLSERVEREXPE
Database=SnapSearchDb
User=AES:nEWjSCtbnMeRmOOC8ZbTBY9QPfF9nzs3cskIj4h/jFo=
Password=AES:fiDBekL1Z1lGIMbned2o8timbFf9e2CBXxTSqKr4f/4=
Encrypt=true
TrustServerCertificate=true